### ISSUE TITLE
Package does not build.

### ISSUE THREAD

**Issue by ArthurSonzogni** [adig-pkgs/ftxui-git#2]
Hello @adi-g15 

Some users reported the package do not build anymore.

I struggled a bit trying arch linux in docker. I was wondering if you could take a look what happens please?
https://aur.archlinux.org/packages/ftxui-git

**Comment by adi-g15** [comment]
> Hello @adi-g15 
> 
> Some users reported the package do not build anymore.
> 
> I struggled a bit trying arch linux in docker. I was wondering if you could take a look what happens please?
> https://aur.archlinux.org/packages/ftxui-git

Okay, sure @ArthurSonzogni, I will try to see what might be the issue 👍

**Comment by adi-g15** [comment]
### UPDATE:

The **reason** was actually a compiler flag, `CXXFLAGS="-Wp,-D_GLIBCXX_ASSERTIONS"`. This is specified by default on Arch Linux systems, inside /etc/makepkg.conf

**The locations causing these are:**
  `DrawBlockOn`, `DrawBlockOff`, `ftxui::Canvas::DrawBlockToggle` functions. (as error showed, ftxui::Canvas::_ZN5ftxui6Canvas11DrawBlockOnEii.part.0 etc).

It was caused by inlining, as `DrawBlockToggle` function is called with same arguments **2,8** at four places in code, so compiler was optimising it by inlining (though `DrawBlockOn` and `DrawBlockOff` weren't used, but for some reason they are also getting inlined, changing Build type to Debug doesn't seem to prevent the inlining), and it **seems to be a problem of out of bound index** (not yet that sure, it seems so)

I will read up on that flag, though it would help if you could check what thing they are accessing and can it be out of bounds accesses @ArthurSonzogni :sweat_smile: .

### To reproduce this error

By the way this should be enough to cause the error

```sh
# Inside build directory
CXXFLAGS="-Wp,-D_GLIBCXX_ASSERTIONS" cmake -DFTXUI_ENABLE_INSTALL=ON -DFTXUI_BUILD_EXAMPLES=OFF -DFTXUI_BUILD_TESTS=OFF -DFTXUI_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
cmake --build ..
```

I found these reasons from basically trial and error... removing one compiler flag at a time from /etc/makepkg.conf, and checking different configs.

> Initially I thought some assignment caused it, and it makes sense given the message containing memcpy.

### An interesting observation

Commenting out assignment to `bit` and `value` (ie. Line 492,494 below) solves one error (out of 3 total) at `Canvas::DrawBlockOff` function. This doesn't remove the cases for others, this was just as I wanted to try if that statement might be causing a big value or something like that.

https://github.com/ArthurSonzogni/FTXUI/blob/d9241435ce9fa3d81f0ea5a0d34c3048883629ee/src/ftxui/dom/canvas.cpp#L481-L496

### Arch Linux custom dockerfile

> > I struggled a bit trying arch linux in docker.
>
> Yes, it requires installing many things, plus a user, I had created a dockerfile for testing arch packages, you may use this (though it's big in size (900 MB, might need ~400 MB to download), I have to use google cloud shell for it:
>
> **docker run -it [ghcr.io/adi-g15/devel-arch:custom](https://github.com/adi-g15/devel-arch/pkgs/container/devel-arch)**
>
> Before doing `makepkg` though, will need to use a non-root user (eg. `su - builder` will be enough on the docker image as it contains the user), or `yay -S ftxui-git` will also work.

**Comment by ArthurSonzogni** [comment]
Wow! That's awesome. Thank you so much 🙏

**Comment by adi-g15** [comment]
As of now, I am failing to see this error on ubuntu (with GCC 10, clang 13), while I can see this on Arch Linux (GCC 12).

> **EDIT: ** I have found another "workaround", it's weird, I don't seem to understand what might be the problem, but here is the workaround:
>
> In all 3 functions mentioned above:
> 
> ```diff
> -    cell.content.character = " ";
> +    cell.content.character.clear();
> +    cell.content.character.push_back(' ');
> ```
>
> What is happening is, the = operator internally calls string::assign, which then calls, string::_M_replace (gcc), which fails at `string::_S_copy(p + n_left, p + 1, 1 - n_left)` (p = this->data(), simplified)... Highly unlikely, but I think this CAN be a bug in gcc, I don't see any problem with FTXUI's code though

For Arch systems, as a **temporary fix**, you can add `CXXFLAGS="$CFLAGS" cmake ... ..` in PKGBUILD, ie.

```diff
@@ -23,7 +23,7 @@ pkgver() {
 build() {
   cd "$srcdir/ftxui"
   mkdir -p build && cd build
-  cmake \
+  CXXFLAGS="$CFLAGS" cmake \
```

By default, in /etc/makepkg.conf, arch has `CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"`, so we manually specify just `CXXFLAGS="$CFLAGS"`, and not the other flag, the errors won't show up. Though we might try to fix the cause later too :sweat_smile: 

Also, since the flag is in /etc/makepkg.conf, it only affects build when installing from AUR, else cloning and building still works.

> As for the flag, this is what the manpage says:
> 
> ![2022-07-18_11-40](https://user-images.githubusercontent.com/37269665/179453831-3074938b-bc26-4dd5-b01b-5bb849bcda84.png)

**Comment by ArthurSonzogni** [comment]
Nice! Thank you very much!

**Comment by adi-g15** [comment]
> Nice! Thank you very much!

:pray:

Now builds fine on both my system and archlinux docker image :+1:. Should this issue be closed?

**Comment by ArthurSonzogni** [comment]
Thanks for the confirmation and your help!
